In [3]:
import numpy as np

In [16]:
tokens = ["Le", "chien","dort"]

embedds={
    "Le": np.array([1, 0]),
    "chien": np.array([0, 1]),
    "dort": np.array([1, 1])
}

X= np.stack([embedds[t] for t in tokens ])


#random Q,K,V matrices
W_q = np.array([[1, 0], [0, 1]]) 
W_k = np.array([[0.5, 1], [1, 0.5]])
W_v = np.array([[1, 1], [0, 1]])
#these numbers are usually learned by the model during training 

#Compute Q, K, V
Q = X @ W_q.T
K = X @ W_k.T
V = X @ W_v.T
#multiply input embeddings with weight matrices to turn them into queries, keys, and values 
#T--> transpose matrix (row becomes column and vice-versa)  to make the matrix shapes match correctly for multiplication.

#compute attention scores between Q and K with dot product 
scores = Q @ K.T #attention scores
scores_scaled = scores / np.sqrt(K.shape[1]) # scale scores to stabilize softmax

# softmax for attention weights 
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=-1, keepdims=True)

att_weight= softmax(scores_scaled)



#explication:
#x= input vector [2,1,0.1]
# find the highest value in x which is m= 2
# e_x: substract each elt of x with m, n = [0,-1,1.9]
# exponentielle of each elt of n= [e^0,e^-1, e^-1.9], e is a constant of approximatly 2.7 use in attention to have positive value. which gives us l= [1,0.3679,0.1496]
# sum of l= j=1.5
# divide each elt of l with j === [0.659,0.242,0.099]
#GOAL: have a weight between O and 1 

output= att_weight @ V

print("Tokens:", tokens)
print("Attention weights:\n", att_weight)
print("Output vectors:\n", output)

Tokens: ['Le', 'chien', 'dort']
Attention weights:
 [[0.22460634 0.31986617 0.45552749]
 [0.31986617 0.22460634 0.45552749]
 [0.20457105 0.20457105 0.59085789]]
Output vectors:
 [[1.45552749 0.77539366]
 [1.45552749 0.68013383]
 [1.59085789 0.79542895]]
